- name: Download and unzip file
  ansible.builtin.unarchive:
    src: "{{ github_project }}/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  changed_when: False

- name: Copy files to runtime directory
  ansible.builtin.copy:
    src: "/tmp/velero-{{ velero_version }}-linux-amd64/velero"
    dest: "/usr/local/bin"
    mode: 0755
    remote_src: yes